# Site settings
title: Askøy Fotballklubb
email: vnystad@gmail.com
description: Askøy Fotballklubb
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://askoyfk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#host: 192.168.1.214


# exclude:
#     - node_modules/test
#
# include:

exclude:
    - feed.xml
    - README.md
    - node_modules/.bin
    - node_modules/browser-sync
    - node_modules/del
    - node_modules/es6-promise
    - node_modules/google-spreadsheet
    - node_modules/gulp
    - node_modules/gulp-autoprefixer
    - node_modules/gulp-convert
    - node_modules/gulp-ext-replace
    - node_modules/gulp-file
    - node_modules/gulp-insert
    - node_modules/gulp-ruby-sass
    - gulpfile.js
    - package.json
    - tasks
    - _sass
    - sass-ny-meny
    - styles
    - index-ny-meny.html
    - bower.json
    - afk-layout



# Collections

collections:
    lag:
        output: true
        permalink: /lag/:path/
        layout: team
#    arrangement:
#        output: true
#        permalink: /arrangement/:path/
#    baner:
#        output: true
#        permalink: /baner/:path/
#    klubben:
#        output: true
#        permalink: /klubben/:path/
