# Site settings
title: Askøy Fotballklubb
email: vnystad@gmail.com
description: Askøy Fotballklubb 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://askoyfk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exlude: ["node_modules", "gulpfile.js", "package.json"]
