# Site settings
title: Askøy Fotballklubb
email: vnystad@gmail.com
description: Askøy Fotballklubb
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://askoyfk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


# exclude:
#     - node_modules/test
#
# include:

exclude:
    - feed.xml
    - README.md
    - node_modules
    - gulpfile.js
    - package.json
    - tasks
    - _sass
    - sass-ny-meny
    - styles
    - index-ny-meny.html
    - bower.json



# Collections

collections:
    test:
        output: true
        permalink: /test/:path/
    lag:
        output: true
        permalink: /lag/:path/
        layout: team
    arrangement:
        output: true
        permalink: /arrangement/:path/
    baner:
        output: true
        permalink: /baner/:path/
    klubben:
        output: true
        permalink: /klubben/:path/
